services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    expose:
      - "9000"  # Laravel should expose FastCGI port
    volumes:
      - ./backend:/var/www/app:delegated
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "8080:80"  # Nginx serves Laravel API and Vue
    volumes:
      - ./backend:/var/www/app # Laravel API files
      - ./frontend/dist:/var/www/frontend # Vue.js built files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx config
    depends_on:
      - php
      - mysql
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-container
    restart: unless-stopped
    # REMOVE PORTS, Vue is served via Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
