services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER:  '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:
